version: "3.7"
services:

  test:
    image: hsac/fitnesse-fixtures-test-jre8:${VERSION}
    environment:
    - RE_RUN_FAILED=true
    command: -DfitnesseSuiteToRun=SampleTests.SlimTests.UtilityFixtures

  test-with-pdf:
    image: hsac/fitnesse-fixtures-test-jre8-with-pdf:${VERSION}
    environment:
    - RE_RUN_FAILED=true
    command: -DfitnesseSuiteToRun=SampleTests.SlimTests.UtilityFixtures

  chrome:
    image: hsac/fitnesse-fixtures-test-jre8-chrome:${VERSION}
    environment:
    - RE_RUN_FAILED=true
    command: -DfitnesseSuiteToRun=SampleTests.SlimTests.BrowserTest

  chrome-with-pdf:
    image: hsac/fitnesse-fixtures-test-jre8-chrome-with-pdf:${VERSION}
    environment:
    - RE_RUN_FAILED=true
    command: -DfitnesseSuiteToRun=SampleTests.SlimTests.BrowserTest

  chrome-suffix:
    image: hsac/fitnesse-fixtures-test-jre8-chrome:${VERSION}-${VERSION_SUFFIX}
    environment:
    - RE_RUN_FAILED=true
    command: -DfitnesseSuiteToRun=SampleTests.SlimTests.BrowserTest

  chrome-with-pdf-suffix:
    image: hsac/fitnesse-fixtures-test-jre8-chrome-with-pdf:${VERSION}-${VERSION_SUFFIX}
    environment:
    - RE_RUN_FAILED=true
    command: -DfitnesseSuiteToRun=SampleTests.SlimTests.BrowserTest
